name: Validate PR

on: 
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '8'
      - name: Checkout Event-Log-Service Repo
        uses: actions/checkout@v2
     
      - run: mvn clean install -U -DskipTests
